### PR TITLE
SLING-12285 adding bind & unbind methods mapping

### PR DESCRIPTION
**Pull request by gagan031992**
Adding bind & unbind methods mapping in reference annotation.
Currently Binding & Unbinding of methods are not working after moving on OSGI R6 annotation.

### CODE REVIEW

**Comment by rombert** [comment]
@gagan031992 - thanks for the PR! Since this is a non-trivial change, can you please open a Jira issue?

https://issues.apache.org/jira/browse/SLING

**Comment by gagan031992** [comment]
Hello @rombert ,

Here is the Sling issue for it.
https://issues.apache.org/jira/browse/SLING-12285

**Comment by rombert** [comment]
Thanks @gagan031992 ! I asked for clarification there.

**Comment by rombert** [comment]
Thanks for the PR and explanation in the Jira issue @gagan031992 , I've merged the fix and will create a release this week.

**Pull request merged**
