### PR TITLE
SLING-12290 - Update tenant module to use parent pom 52

### PR DESCRIPTION
**Pull request by rombert**

### CODE REVIEW

**Comment by kwin** [comment]
Why not 60?

**Comment by rombert** [comment]
Because we still need to target Java 8.

**Comment by kwin** [comment]
What makes you think this is not supported with Parent 60?

Compare with https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=284790344.

**Comment by rombert** [comment]
You're right, I had it in my had that we require Java 17 for running, but it's for building only. Need to do more parent pom updates to help me remember :-)

**Pull request merged**
